#ItemID of the item to sell
Item: 266
#ItemID of the selling tool
SellTool: 283
#base sale price of the item (this is the maximum)
base: 100
#minimum sale price of the item
minimum: 10
#how long to keep records (in days)
duration: 7
#decrease in price per item sold
ratio: 1/10
#MySQL, SQLite, or none
#none infers static pricing (always uses base price)
Data: MySQL
MySQL:
    database: minecraft
    hostname: localhost
    port: 3306
    username: mc
    password: pass