name: GoldStandard
main: com.bukkit.BallisticBuddha.GoldStandard.GoldStandard
version: 0.7.1
author: BallisticBuddha
commands:
  gsworth:
    aliases: gsprice
    description: Used for checking the current price of the item
    usage: |
           /gsworth
  gsclear:
    aliases: gsreset
    description: Used for resetting the price of the item (clearing all sale records)
    usage: |
           /gsclear
  gssell:
    aliases: 
        - gsell
    description: Sell a specified number of the item directly from your inventory
    usage: |
           /gssell <amount>
  gsbuy:
      aliases: 
          - gbuy
      description: Buy the specified amount of gold
      usage: |
             /gsbuy <amount>