name: GoldStandard
main: com.bukkit.BallisticBuddha.GoldStandard.GoldStandard
version: 0.8
author: BallisticBuddha
commands:
  gsworth:
    aliases: gsprice
    description: Used for checking the current price of the item
    usage: |
           /gsworth
  gsclear:
    aliases: gsreset
    description: Used for resetting the price of the item (clearing all sale records)
    usage: |
           /gsclear
  gssell:
    aliases: 
        - gsell
    description: Sell a specified number of the item directly from your inventory
    usage: |
           /gssell <amount>[option]
              (append a ~ to the number to include blocks in the sale)
              (or * to get your "change" in blocks)
               e.g. /gssell 20~
  gsbuy:
      aliases: 
          - gbuy
      description: Buy the specified amount of gold
      usage: |
             /gsbuy <amount>
  gshistory:
      aliases: 
          - ghistory
      description: Displays history of GoldStandard transactions (defaults to net)
      usage: |
             /gshistory <itemID> [sales(+)|purchases(-)|net(blank)]
                 (you can subsitute the type word with the symbol)
